"""
Market brief generator for the Daily Agri-News Digest.

Produces the "day in 90 seconds" summary that sits on top of the digest.
It is generated by Haiku from the day's accepted items and then verified
before it ships:

  1. Generate  — Haiku writes a short, structured brief (tool-use JSON).
  2. Verify    — cheap deterministic checks (em dash, banned words, length,
                 negative-parallelism) + a second Haiku pass that flags any
                 claim the source summaries do not support.
  3. Fail-safe — if the brief still fails after one regeneration, return None
                 and the digest ships without it. A missing brief beats a
                 confident-but-wrong one.

The brief is intentionally a free narrative on top of the digest: its section
labels (Markets, Fertilizer and energy, ...) are a reading map, not a 1:1
mirror of the classifier's categories.
"""

import asyncio
import logging
import re
from typing import Optional

import anthropic

from models import (
    Article, CompanySignal, Publication, MarketBrief, BriefSection, RunMetrics,
)
from constants import (
    CLAUDE_MODEL_PRIMARY, CLAUDE_MODEL_FALLBACK, CLAUDE_MAX_RETRIES,
    BRIEF_MAX_WORDS, BRIEF_BANNED_WORDS, BRIEF_NEG_PARALLELISM, BRIEF_SECTION_ORDER,
)

logger = logging.getLogger("market_brief")


# ── Prompts ────────────────────────────────────────────────────────

BRIEF_SYSTEM_PROMPT = f"""You write the "Market brief" at the top of an internal daily agri-news digest for the staff of Hyperplan, an agri-tech company. The brief lets a reader get the day's market picture without reading every article. It is a neutral synthesis of the news, not company-specific commentary.

VOICE (hard rules):
- Direct, data-driven, no hype. Lead with the takeaway.
- Short sentences. Numbers as digits.
- Never use em dashes. Use commas, periods, colons, semicolons, or parentheses.
- Never use negative-parallelism or reframe constructions ("Not X, Y", "It's not about X, it's about Y", or any sentence that negates one framing then asserts another). Keep only the positive claim.
- Never use these words: {", ".join(BRIEF_BANNED_WORDS)}.
- No rule-of-three padding. Use the one or two facts that matter.

ACCURACY (critical):
- Only restate facts present in the source summaries provided.
- Never assert causation or a relationship between two facts unless a summary states it.
- Never add specifics (place names, numbers, dates, company names) that are not in the sources.
- If a section has nothing material today, omit it. Do not pad.

STRUCTURE:
- A 2-sentence top-line takeaway.
- Then up to 6 short sections, each 2-3 sentences, chosen and ordered from: {", ".join(BRIEF_SECTION_ORDER)}. Use a section only if the day's news supports it.
- Markets may run up to 3 sentences; all other sections at most 2.
- Whole brief at most {BRIEF_MAX_WORDS} words.
Return the brief via the write_brief tool only."""

WRITE_BRIEF_TOOL = {
    "name": "write_brief",
    "description": "Return the market brief as a takeaway plus labelled sections.",
    "input_schema": {
        "type": "object",
        "properties": {
            "takeaway": {
                "type": "string",
                "description": "2-sentence top-line takeaway for the whole day.",
            },
            "sections": {
                "type": "array",
                "description": "Ordered brief sections.",
                "items": {
                    "type": "object",
                    "properties": {
                        "label": {"type": "string", "description": "Section label, e.g. 'Markets'."},
                        "text": {"type": "string", "description": "2-3 sentence summary for this section."},
                    },
                    "required": ["label", "text"],
                },
            },
        },
        "required": ["takeaway", "sections"],
    },
}

AUDIT_SYSTEM_PROMPT = """You are a fact-checker. You are given a draft market brief and the source summaries it was built from. Your only job is to find claims in the brief that the sources do not support.

Flag every instance of:
1. A claim not supported by any source summary.
2. A causal or relational link ("because", "dragging", "due to", "as a result", "after", "driving") that the sources do not state.
3. An added specific (place name, number, date, company) absent from the sources.

Be strict but do not invent problems. If the brief is fully supported, return an empty list. Return your findings via the report_issues tool only."""

REPORT_ISSUES_TOOL = {
    "name": "report_issues",
    "description": "Report unsupported claims found in the brief.",
    "input_schema": {
        "type": "object",
        "properties": {
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string", "description": "The offending phrase from the brief."},
                        "reason": {"type": "string", "description": "Why the sources do not support it."},
                    },
                    "required": ["text", "reason"],
                },
            },
        },
        "required": ["issues"],
    },
}


# ── Deterministic checks ───────────────────────────────────────────

def _brief_text(brief: MarketBrief) -> str:
    """Flatten the brief to a single string for checking."""
    return " ".join([brief.takeaway] + [s.text for s in brief.sections])


def deterministic_issues(brief: MarketBrief) -> list[str]:
    """Return a list of hard rule violations (em dash, banned words, length)."""
    text = _brief_text(brief)
    issues: list[str] = []

    if "—" in text or "–" in text:
        issues.append("Contains an em/en dash.")

    word_count = len(text.split())
    if word_count > BRIEF_MAX_WORDS:
        issues.append(f"Too long: {word_count} words (max {BRIEF_MAX_WORDS}).")

    lowered = text.lower()
    for word in BRIEF_BANNED_WORDS:
        if re.search(rf"\b{re.escape(word)}\b", lowered):
            issues.append(f"Banned word: '{word}'.")

    return issues


def soft_warnings(brief: MarketBrief) -> list[str]:
    """Return non-blocking negative-parallelism warnings (logged only)."""
    lowered = _brief_text(brief).lower()
    return [f"Possible negative-parallelism: '{p}'." for p in BRIEF_NEG_PARALLELISM if p in lowered]


_NUMBER_RE = re.compile(r"\d[\d.,]*")

# Sentence splitter for salvage. Keeps the delimiter off; good enough for the
# short, plain sentences the brief produces.
_SENTENCE_RE = re.compile(r"(?<=[.!?])\s+")

# Style-only banned words mapped to neutral equivalents. A single banned word
# is a style slip, never an accuracy problem, so we rewrite it in place instead
# of dropping the brief. Words with no clean synonym are removed.
BANNED_WORD_REPLACEMENTS = {
    "leverage": "use",
    "landscape": "market",
    "robust": "strong",
    "seamless": "smooth",
    "game-changer": "major shift",
    "cutting-edge": "advanced",
    "unlock": "open up",
    "harness": "use",
    "pivotal": "key",
    "crucial": "key",
    "underscore": "show",
    "navigate": "handle",
    "delve": "look",
    "realm": "area",
    "testament": "sign",
    "foster": "support",
    "empower": "enable",
    "streamline": "simplify",
    "elevate": "raise",
    "transformative": "major",
    "dynamic": "shifting",
    "optimize": "improve",
}


def _number_is_grounded(norm: str, src_nospace: str) -> bool:
    """True if a normalized number figure is supported by the source text.

    Tolerant on purpose: exact standalone match, or the same value with a
    trailing ".0" dropped, or an integer that the source carries with a decimal
    tail (brief rounds "2.3" to "2"). Reverse rounding is not accepted, since
    inventing a decimal that no source states is the risk we guard against.
    """
    # Exact standalone figure (not a substring of a longer number).
    if re.search(rf"(?<!\d){re.escape(norm)}(?!\d)", src_nospace):
        return True
    # "5.0" grounded by "5".
    if norm.endswith(".0"):
        base = norm[:-2]
        if re.search(rf"(?<!\d){re.escape(base)}(?!\d)", src_nospace):
            return True
    # Integer in the brief grounded by a decimal in the source ("2" from "2.3").
    if "." not in norm and re.search(rf"(?<!\d){re.escape(norm)}\.\d", src_nospace):
        return True
    return False


def _structural_number(tok: str, text: str) -> bool:
    """True for reading-aid numbers that are not statistics.

    Quarters (Q3), halves (H1), top-N lists, group labels (G7, G20), and
    duration phrases (3-week, 2-day) are structure, not claims, so they should
    not be checked against the sources.
    """
    esc = re.escape(tok)
    patterns = [
        rf"[QH]{esc}\b",                              # Q3, H1
        rf"\btop[\s-]{esc}\b",                        # top 10
        rf"\bG{esc}\b",                               # G7, G20
        rf"{esc}[\s-](?:week|day|month|year|quarter)", # 3-week
    ]
    return any(re.search(p, text, re.IGNORECASE) for p in patterns)


def _ungrounded_tokens(text: str, src_nospace: str) -> list[str]:
    """Return the original number tokens in `text` not supported by the source."""
    out: list[str] = []
    seen: set[str] = set()
    for tok in _NUMBER_RE.findall(text):
        norm = tok.strip(".,").replace(",", "")
        if len(norm) < 2 or norm in seen:
            continue
        if re.fullmatch(r"(19|20)\d\d", norm):       # skip years
            continue
        seen.add(norm)
        if _structural_number(tok, text):
            continue
        if not _number_is_grounded(norm, src_nospace):
            out.append(tok)
    return out


def ungrounded_numbers(brief: MarketBrief, source_text: str) -> list[str]:
    """Flag numbers in the brief that the source summaries do not support.

    Cheap, reliable guard against the real risk: a fabricated statistic (e.g.
    "prices down 20%" when no source says 20%). This is the only hard accuracy
    gate; the LLM claim-audit is advisory because it over-flagged ordinary
    synthesis and suppressed the brief on most days.
    """
    src = source_text.replace(",", "")
    return [f"Number '{t}' not in sources." for t in _ungrounded_tokens(_brief_text(brief), src)]


# ── Deterministic auto-fixes (style only, never a reason to drop) ────

def _autofix_style(brief: MarketBrief) -> MarketBrief:
    """Repair style-only violations in place so they never drop the brief.

    Handles em/en dashes and banned AI-tell vocabulary (rewritten to neutral
    equivalents), then trims trailing sections if the brief runs over length.
    Accuracy is untouched: no numbers, names, or claims are changed.
    """
    def fix(text: str) -> str:
        text = text.replace("—", ", ").replace("–", ", ")
        for word, repl in BANNED_WORD_REPLACEMENTS.items():
            def _sub(m: re.Match) -> str:
                w = m.group(0)
                return repl.capitalize() if w[0].isupper() else repl
            text = re.sub(rf"\b{re.escape(word)}\b", _sub, text, flags=re.IGNORECASE)
        # Any banned word without a mapping: drop it.
        for word in BRIEF_BANNED_WORDS:
            if word not in BANNED_WORD_REPLACEMENTS:
                text = re.sub(rf"\b{re.escape(word)}\b", "", text, flags=re.IGNORECASE)
        # Clean up spacing left behind by replacements.
        text = re.sub(r"\s+,", ",", text)
        text = re.sub(r",\s*,", ",", text)
        text = re.sub(r"\s{2,}", " ", text).strip()
        return text

    brief.takeaway = fix(brief.takeaway)
    for s in brief.sections:
        s.text = fix(s.text)

    # Length: trim whole sections from the end until under the cap. The
    # takeaway is always kept.
    while len(_brief_text(brief).split()) > BRIEF_MAX_WORDS and brief.sections:
        brief.sections.pop()

    return brief


def _strip_ungrounded_sentences(brief: MarketBrief, source_text: str) -> Optional[MarketBrief]:
    """Remove only the sentences carrying an ungrounded number, keep the rest.

    Last-resort salvage so one bad figure does not kill the whole brief. Returns
    a brief if anything material survives (a non-empty takeaway and at least one
    section), otherwise None.
    """
    src = source_text.replace(",", "")

    def clean(text: str) -> str:
        kept = [s for s in _SENTENCE_RE.split(text) if s and not _ungrounded_tokens(s, src)]
        return " ".join(kept).strip()

    takeaway = clean(brief.takeaway)
    sections = []
    for s in brief.sections:
        t = clean(s.text)
        if t:
            sections.append(BriefSection(label=s.label, text=t))

    # If the takeaway lost all its sentences, promote the first surviving
    # section's text so the brief still opens with a line.
    if not takeaway and sections:
        takeaway = sections[0].text

    salvaged = MarketBrief(takeaway=takeaway, sections=sections)
    return salvaged if salvaged.has_content else None


# ── Source text ────────────────────────────────────────────────────

def _build_source_text(
    articles: list[Article],
    client_signals: list[CompanySignal],
    prospect_signals: list[CompanySignal],
    publications: list[Publication],
) -> str:
    """Assemble the grouped summaries that the brief is written from."""
    by_cat: dict[str, list[Article]] = {}
    for a in articles:
        by_cat.setdefault(a.category.value, []).append(a)

    parts: list[str] = []
    parts.append(
        f"AT A GLANCE: {len(publications)} publications, {len(articles)} articles, "
        f"{len(client_signals)} client signals, {len(prospect_signals)} prospect signals.\n"
    )

    parts.append("NEWS (grouped by category):")
    for cat, items in sorted(by_cat.items(), key=lambda x: -len(x[1])):
        parts.append(f"\n## {cat} ({len(items)})")
        for a in items:
            summary = a.summary.replace("\n", " ").strip()
            parts.append(f"- {a.title} | {summary}")

    # Official publications carry the acreage / yield / production figures the
    # brief is asked to cover under "Acreage and crop shifts". They must be in
    # the grounding text, otherwise any number the brief quotes from them gets
    # flagged as ungrounded and the whole brief is dropped on publication-heavy
    # days. This was the main cause of the brief going missing.
    if publications:
        parts.append("\nOFFICIAL PUBLICATIONS:")
        for p in publications:
            summary = (p.summary or "").replace("\n", " ").strip()
            country = f" [{p.country}]" if p.country else ""
            parts.append(f"- {p.title}{country} | {summary}")

    if client_signals:
        parts.append("\nCLIENT SIGNALS:")
        for s in client_signals:
            parts.append(f"- {s.company_name}: {s.title} | {s.summary.replace(chr(10), ' ').strip()}")
    if prospect_signals:
        parts.append("\nPROSPECT SIGNALS:")
        for s in prospect_signals:
            parts.append(f"- {s.company_name}: {s.title} | {s.summary.replace(chr(10), ' ').strip()}")

    return "\n".join(parts)


# ── Generator ──────────────────────────────────────────────────────

class MarketBriefGenerator:
    """Generates and verifies the market brief. Fails open (returns None)."""

    def __init__(self, api_key: str, metrics: RunMetrics):
        self.client = anthropic.AsyncAnthropic(api_key=api_key)
        self.metrics = metrics
        self._model = CLAUDE_MODEL_PRIMARY
        self._last_issues: list[str] = []
        self.last_status: str = "not run"

    def _track(self, response) -> None:
        self.metrics.input_tokens += response.usage.input_tokens
        self.metrics.output_tokens += response.usage.output_tokens
        cache_read = getattr(response.usage, "cache_read_input_tokens", None) or 0
        self.metrics.cache_read_tokens += cache_read

    async def _call(self, system: str, user: str, tool: dict, tool_name: str) -> Optional[dict]:
        """One tool-use call with retries and model fallback. Returns tool input or None."""
        for attempt in range(CLAUDE_MAX_RETRIES):
            try:
                response = await self.client.messages.create(
                    model=self._model,
                    max_tokens=2000,
                    temperature=0.2,
                    system=system,
                    messages=[{"role": "user", "content": user}],
                    tools=[tool],
                    tool_choice={"type": "tool", "name": tool_name},
                )
                self._track(response)
                block = next((b for b in response.content if b.type == "tool_use"), None)
                return block.input if block else None
            except anthropic.RateLimitError:
                wait = 2 ** (attempt + 1)
                logger.warning(f"Brief: rate limited, retry in {wait}s")
                await asyncio.sleep(wait)
            except anthropic.APIError as e:
                if attempt == CLAUDE_MAX_RETRIES - 1:
                    if self._model != CLAUDE_MODEL_FALLBACK:
                        self._model = CLAUDE_MODEL_FALLBACK
                        logger.info(f"Brief: switching to fallback model {CLAUDE_MODEL_FALLBACK}")
                        return await self._call(system, user, tool, tool_name)
                    logger.error(f"Brief: API error, giving up: {e}")
                    return None
                await asyncio.sleep(1)
            except Exception as e:
                logger.error(f"Brief: unexpected error: {e}")
                return None
        return None

    def _parse(self, data: dict) -> Optional[MarketBrief]:
        if not data:
            return None
        sections = [
            BriefSection(label=str(s.get("label", "")).strip(), text=str(s.get("text", "")).strip())
            for s in data.get("sections", [])
            if s.get("label") and s.get("text")
        ]
        brief = MarketBrief(takeaway=str(data.get("takeaway", "")).strip(), sections=sections)
        return brief if brief.has_content else None

    async def _audit(self, brief: MarketBrief, source_text: str) -> list[str]:
        """Haiku claim-audit. Returns a list of unsupported-claim descriptions."""
        user = f"DRAFT BRIEF:\n{_brief_text(brief)}\n\nSOURCE SUMMARIES:\n{source_text}"
        data = await self._call(AUDIT_SYSTEM_PROMPT, user, REPORT_ISSUES_TOOL, "report_issues")
        if not data:
            # Audit itself failed: treat as no blocking issues but log it.
            logger.warning("Brief: audit call failed, proceeding without it")
            return []
        return [f"{i.get('text', '')} ({i.get('reason', '')})" for i in data.get("issues", [])]

    async def generate(
        self,
        date: str,
        articles: list[Article],
        client_signals: list[CompanySignal],
        prospect_signals: list[CompanySignal],
        publications: list[Publication],
    ) -> Optional[MarketBrief]:
        """Generate, verify, and return the brief, or None if it can't be trusted."""
        if not articles:
            logger.info("Brief: no articles, skipping")
            self.last_status = "omitted (no articles)"
            return None

        source_text = _build_source_text(articles, client_signals, prospect_signals, publications)
        base_user = f"Today is {date}.\n\nWrite the market brief from these sources:\n\n{source_text}"

        last_brief: Optional[MarketBrief] = None
        attempts = 3  # one generation + two corrective regenerations
        for attempt in range(attempts):
            user = base_user
            if attempt > 0 and self._last_issues:
                user += (
                    "\n\nYour previous draft quoted numbers the sources do not support. "
                    "Rewrite so every figure comes straight from a source summary, or drop "
                    "the figure. Do not introduce new claims:\n- " + "\n- ".join(self._last_issues)
                )

            data = await self._call(BRIEF_SYSTEM_PROMPT, user, WRITE_BRIEF_TOOL, "write_brief")
            brief = self._parse(data)
            if not brief:
                logger.warning("Brief: generation returned nothing usable")
                self.last_status = "omitted (generation empty)"
                return None

            # Style is repaired deterministically (em dash, banned words,
            # length): a style slip is never a reason to drop the brief.
            brief = _autofix_style(brief)
            last_brief = brief

            for w in soft_warnings(brief):
                logger.info(f"Brief soft warning: {w}")
            for note in await self._audit(brief, source_text):
                logger.info(f"Brief audit note (non-blocking): {note}")

            # Only accuracy (ungrounded numbers) gates the brief.
            accuracy = ungrounded_numbers(brief, source_text)
            if not accuracy:
                self.last_status = f"included ({len(brief.sections)} sections)"
                logger.info(f"Brief verified ({len(brief.sections)} sections)")
                return brief

            self._last_issues = accuracy
            logger.warning(f"Brief attempt {attempt + 1}: {len(accuracy)} ungrounded number(s): {accuracy}")

        # Regeneration did not clear every figure. Rather than drop the whole
        # brief, strip only the sentences carrying an ungrounded number and ship
        # the rest. A trimmed-but-true brief beats no brief on busy days.
        if last_brief is not None:
            salvaged = _strip_ungrounded_sentences(last_brief, source_text)
            if salvaged is not None:
                salvaged = _autofix_style(salvaged)
                if not ungrounded_numbers(salvaged, source_text):
                    self.last_status = f"included (salvaged, {len(salvaged.sections)} sections)"
                    logger.info("Brief: shipped salvaged version with ungrounded sentences removed")
                    return salvaged

        # Nothing material survived the salvage: fail safe.
        self.last_status = f"omitted ({'; '.join(self._last_issues)[:120]})"
        logger.warning("Brief: no groundable content after salvage, shipping without it")
        return None
