"""
Market brief generator for the Daily Agri-News Digest.

Produces the "day in 90 seconds" summary that sits on top of the digest.
It is generated by Haiku from the day's accepted items and then verified
before it ships:

  1. Generate  — Haiku writes a short, structured brief (tool-use JSON).
  2. Verify    — cheap deterministic checks (em dash, banned words, length,
                 negative-parallelism) + a second Haiku pass that flags any
                 claim the source summaries do not support.
  3. Fail-safe — if the brief still fails after one regeneration, return None
                 and the digest ships without it. A missing brief beats a
                 confident-but-wrong one.

The brief is intentionally a free narrative on top of the digest: its section
labels (Markets, Fertilizer and energy, ...) are a reading map, not a 1:1
mirror of the classifier's categories.
"""

import asyncio
import logging
import re
from typing import Optional

import anthropic

from models import (
    Article, CompanySignal, Publication, MarketBrief, BriefSection, RunMetrics,
)
from constants import (
    CLAUDE_MODEL_PRIMARY, CLAUDE_MODEL_FALLBACK, CLAUDE_MAX_RETRIES,
    BRIEF_MAX_WORDS, BRIEF_BANNED_WORDS, BRIEF_NEG_PARALLELISM, BRIEF_SECTION_ORDER,
)

logger = logging.getLogger("market_brief")


# ── Prompts ────────────────────────────────────────────────────────

BRIEF_SYSTEM_PROMPT = f"""You write the "Market brief" at the top of an internal daily agri-news digest for the staff of Hyperplan, an agri-tech company. The brief lets a reader get the day's market picture without reading every article. It is a neutral synthesis of the news, not company-specific commentary.

VOICE (hard rules):
- Direct, data-driven, no hype. Lead with the takeaway.
- Short sentences. Numbers as digits.
- Never use em dashes. Use commas, periods, colons, semicolons, or parentheses.
- Never use negative-parallelism or reframe constructions ("Not X, Y", "It's not about X, it's about Y", or any sentence that negates one framing then asserts another). Keep only the positive claim.
- Never use these words: {", ".join(BRIEF_BANNED_WORDS)}.
- No rule-of-three padding. Use the one or two facts that matter.

ACCURACY (critical):
- Only restate facts present in the source summaries provided.
- Never assert causation or a relationship between two facts unless a summary states it.
- Never add specifics (place names, numbers, dates, company names) that are not in the sources.
- If a section has nothing material today, omit it. Do not pad.

STRUCTURE:
- A 2-sentence top-line takeaway.
- Then up to 6 short sections, each 2-3 sentences, chosen and ordered from: {", ".join(BRIEF_SECTION_ORDER)}. Use a section only if the day's news supports it.
- Markets may run up to 3 sentences; all other sections at most 2.
- Whole brief at most {BRIEF_MAX_WORDS} words.
Return the brief via the write_brief tool only."""

WRITE_BRIEF_TOOL = {
    "name": "write_brief",
    "description": "Return the market brief as a takeaway plus labelled sections.",
    "input_schema": {
        "type": "object",
        "properties": {
            "takeaway": {
                "type": "string",
                "description": "2-sentence top-line takeaway for the whole day.",
            },
            "sections": {
                "type": "array",
                "description": "Ordered brief sections.",
                "items": {
                    "type": "object",
                    "properties": {
                        "label": {"type": "string", "description": "Section label, e.g. 'Markets'."},
                        "text": {"type": "string", "description": "2-3 sentence summary for this section."},
                    },
                    "required": ["label", "text"],
                },
            },
        },
        "required": ["takeaway", "sections"],
    },
}

AUDIT_SYSTEM_PROMPT = """You are a fact-checker. You are given a draft market brief and the source summaries it was built from. Your only job is to find claims in the brief that the sources do not support.

Flag every instance of:
1. A claim not supported by any source summary.
2. A causal or relational link ("because", "dragging", "due to", "as a result", "after", "driving") that the sources do not state.
3. An added specific (place name, number, date, company) absent from the sources.

Be strict but do not invent problems. If the brief is fully supported, return an empty list. Return your findings via the report_issues tool only."""

REPORT_ISSUES_TOOL = {
    "name": "report_issues",
    "description": "Report unsupported claims found in the brief.",
    "input_schema": {
        "type": "object",
        "properties": {
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string", "description": "The offending phrase from the brief."},
                        "reason": {"type": "string", "description": "Why the sources do not support it."},
                    },
                    "required": ["text", "reason"],
                },
            },
        },
        "required": ["issues"],
    },
}


# ── Deterministic checks ───────────────────────────────────────────

def _brief_text(brief: MarketBrief) -> str:
    """Flatten the brief to a single string for checking."""
    return " ".join([brief.takeaway] + [s.text for s in brief.sections])


def deterministic_issues(brief: MarketBrief) -> list[str]:
    """Return a list of hard rule violations (em dash, banned words, length)."""
    text = _brief_text(brief)
    issues: list[str] = []

    if "—" in text or "–" in text:
        issues.append("Contains an em/en dash.")

    word_count = len(text.split())
    if word_count > BRIEF_MAX_WORDS:
        issues.append(f"Too long: {word_count} words (max {BRIEF_MAX_WORDS}).")

    lowered = text.lower()
    for word in BRIEF_BANNED_WORDS:
        if re.search(rf"\b{re.escape(word)}\b", lowered):
            issues.append(f"Banned word: '{word}'.")

    return issues


def soft_warnings(brief: MarketBrief) -> list[str]:
    """Return non-blocking negative-parallelism warnings (logged only)."""
    lowered = _brief_text(brief).lower()
    return [f"Possible negative-parallelism: '{p}'." for p in BRIEF_NEG_PARALLELISM if p in lowered]


# ── Source text ────────────────────────────────────────────────────

def _build_source_text(
    articles: list[Article],
    client_signals: list[CompanySignal],
    prospect_signals: list[CompanySignal],
    publications: list[Publication],
) -> str:
    """Assemble the grouped summaries that the brief is written from."""
    by_cat: dict[str, list[Article]] = {}
    for a in articles:
        by_cat.setdefault(a.category.value, []).append(a)

    parts: list[str] = []
    parts.append(
        f"AT A GLANCE: {len(publications)} publications, {len(articles)} articles, "
        f"{len(client_signals)} client signals, {len(prospect_signals)} prospect signals.\n"
    )

    parts.append("NEWS (grouped by category):")
    for cat, items in sorted(by_cat.items(), key=lambda x: -len(x[1])):
        parts.append(f"\n## {cat} ({len(items)})")
        for a in items:
            summary = a.summary.replace("\n", " ").strip()
            parts.append(f"- {a.title} | {summary}")

    if client_signals:
        parts.append("\nCLIENT SIGNALS:")
        for s in client_signals:
            parts.append(f"- {s.company_name}: {s.title} | {s.summary.replace(chr(10), ' ').strip()}")
    if prospect_signals:
        parts.append("\nPROSPECT SIGNALS:")
        for s in prospect_signals:
            parts.append(f"- {s.company_name}: {s.title} | {s.summary.replace(chr(10), ' ').strip()}")

    return "\n".join(parts)


# ── Generator ──────────────────────────────────────────────────────

class MarketBriefGenerator:
    """Generates and verifies the market brief. Fails open (returns None)."""

    def __init__(self, api_key: str, metrics: RunMetrics):
        self.client = anthropic.AsyncAnthropic(api_key=api_key)
        self.metrics = metrics
        self._model = CLAUDE_MODEL_PRIMARY
        self._last_issues: list[str] = []

    def _track(self, response) -> None:
        self.metrics.input_tokens += response.usage.input_tokens
        self.metrics.output_tokens += response.usage.output_tokens
        cache_read = getattr(response.usage, "cache_read_input_tokens", None) or 0
        self.metrics.cache_read_tokens += cache_read

    async def _call(self, system: str, user: str, tool: dict, tool_name: str) -> Optional[dict]:
        """One tool-use call with retries and model fallback. Returns tool input or None."""
        for attempt in range(CLAUDE_MAX_RETRIES):
            try:
                response = await self.client.messages.create(
                    model=self._model,
                    max_tokens=1024,
                    temperature=0.2,
                    system=system,
                    messages=[{"role": "user", "content": user}],
                    tools=[tool],
                    tool_choice={"type": "tool", "name": tool_name},
                )
                self._track(response)
                block = next((b for b in response.content if b.type == "tool_use"), None)
                return block.input if block else None
            except anthropic.RateLimitError:
                wait = 2 ** (attempt + 1)
                logger.warning(f"Brief: rate limited, retry in {wait}s")
                await asyncio.sleep(wait)
            except anthropic.APIError as e:
                if attempt == CLAUDE_MAX_RETRIES - 1:
                    if self._model != CLAUDE_MODEL_FALLBACK:
                        self._model = CLAUDE_MODEL_FALLBACK
                        logger.info(f"Brief: switching to fallback model {CLAUDE_MODEL_FALLBACK}")
                        return await self._call(system, user, tool, tool_name)
                    logger.error(f"Brief: API error, giving up: {e}")
                    return None
                await asyncio.sleep(1)
            except Exception as e:
                logger.error(f"Brief: unexpected error: {e}")
                return None
        return None

    def _parse(self, data: dict) -> Optional[MarketBrief]:
        if not data:
            return None
        sections = [
            BriefSection(label=str(s.get("label", "")).strip(), text=str(s.get("text", "")).strip())
            for s in data.get("sections", [])
            if s.get("label") and s.get("text")
        ]
        brief = MarketBrief(takeaway=str(data.get("takeaway", "")).strip(), sections=sections)
        return brief if brief.has_content else None

    async def _audit(self, brief: MarketBrief, source_text: str) -> list[str]:
        """Haiku claim-audit. Returns a list of unsupported-claim descriptions."""
        user = f"DRAFT BRIEF:\n{_brief_text(brief)}\n\nSOURCE SUMMARIES:\n{source_text}"
        data = await self._call(AUDIT_SYSTEM_PROMPT, user, REPORT_ISSUES_TOOL, "report_issues")
        if not data:
            # Audit itself failed: treat as no blocking issues but log it.
            logger.warning("Brief: audit call failed, proceeding without it")
            return []
        return [f"{i.get('text', '')} ({i.get('reason', '')})" for i in data.get("issues", [])]

    async def generate(
        self,
        date: str,
        articles: list[Article],
        client_signals: list[CompanySignal],
        prospect_signals: list[CompanySignal],
        publications: list[Publication],
    ) -> Optional[MarketBrief]:
        """Generate, verify, and return the brief, or None if it can't be trusted."""
        if not articles:
            logger.info("Brief: no articles, skipping")
            return None

        source_text = _build_source_text(articles, client_signals, prospect_signals, publications)
        base_user = f"Today is {date}.\n\nWrite the market brief from these sources:\n\n{source_text}"

        for attempt in range(2):  # one generation + one corrective regeneration
            user = base_user
            if attempt == 1 and self._last_issues:
                user += (
                    "\n\nYour previous draft had these problems. Fix them: remove or correct "
                    "each, and do not introduce new claims:\n- " + "\n- ".join(self._last_issues)
                )

            data = await self._call(BRIEF_SYSTEM_PROMPT, user, WRITE_BRIEF_TOOL, "write_brief")
            brief = self._parse(data)
            if not brief:
                logger.warning("Brief: generation returned nothing usable")
                return None

            det = deterministic_issues(brief)
            for w in soft_warnings(brief):
                logger.info(f"Brief soft warning: {w}")
            audit = await self._audit(brief, source_text)

            self._last_issues = det + audit
            if not self._last_issues:
                logger.info(f"Brief verified clean ({len(brief.sections)} sections)")
                return brief

            logger.warning(
                f"Brief attempt {attempt + 1}: {len(det)} format + {len(audit)} accuracy issues"
            )

        # Still failing after the corrective pass: fail safe.
        logger.warning("Brief: failed verification after regeneration, shipping without it")
        return None
